### ISSUE TITLE
Blokada blocks all downloads in the stock LineageOS browser and all F-Droid browsers.

### ISSUE THREAD

**Issue by Herbstfreud** [blokadaorg/blokada#209]
### Steps to reproduce
1. Download a browser from F-Droid (for example Firefox Klar, JumpGo, DuckduckGo browser, Privacy Browser...) or use the stock browser from LineageOS 14.1
2. Go to a websearch (for example Duckduckgo) and search for a picture ("test") while Blokada activated (Standard DNS, just standard blacklist).
3. Try to download the picture to the phone.

### Expected behaviour

The download icon in the status bar should appear, after the download the picture should be located in the download folder on the smartphone (or in the folder you have set in the browser manually).

### Actual behaviour

The download icon appears for a blink of an eye and disappears again. The downloaded file can be found in the download folder. After several minutes the download icon appears again, together with the message that the download failed. With Blokada disabled same situation works, permissions have also been given to the browsers (if they have been asked for this, e.g. for storage). With some browsers (Chrome, Yuzu,...) from Play Store it works also with Blokada enabled.

### Configuration
1. Blokada version
3.3

2. Device model
Nexus 5
(also LG G4, Samsung Galaxy S2, Samsung Galaxy A5-2017)

3. Android version / ROM
All listed devices with latest LineageOS 14.1

### Questions
1. How long have you been using Blokada? 
Since beginning of 2018.

2. How long time ago has the problem started to happen? 
Since the beginning.

3.  How often does this problem happen to you?
Everytime.

**Comment by Avizini** [comment]
Coudnt reproduce this!

Have you enabled Block connections without VPN option?

Have you tried whitelisting apps within Blokada?

**Comment by Herbstfreud** [comment]
What exactly do you mean with your first question?

Whitelisting the browser in Blokada or disabling Blokada are a theoretical solutin. I can use the mentioned browser (for example the stock LineageOS Browser) then. But whitelisting the browser in an Adblocker App is not really useful I think... ;) Other browsers like Chrome work without whitelisting.

I've forgot to mention that on the Samsung A5-2017 there is no LineageOS, just the stock Android 7, because I don't want to flash my company phone...

**Comment by Avizini** [comment]
There is an option to make the vpn as always on vpn. Below that there is another option saying "Block connections without VPN", I don't know why but after enabling that option Blokada causes the same issue.

I am asking you to whitelist the download manager and not the browser, try whitelisting the download manager and then try again.

**Comment by Herbstfreud** [comment]
I have a German Blokada. Is it is possible that you mean the switch "Nur online", left of the hosts counter? It makes no difference for me in this case, whether the switch is on the left or right side.

Whitelisting the Download Manager has no Effect... also whitelisting of "Downloads" not.

**Comment by Avizini** [comment]
No not that, I dunno how it is with Android 7. There should be a option in VPN Settings where it should ask if you want to set it as always on vpn...

Can you record this and upload the video? There is an app on fdroid called [ScreenCam](https://f-droid.org/packages/com.orpheusdroid.screenrecorder/)

I guess Chrome has its own download manager and is not using android download manager, have you tried with "Fennec F-Droid" ? If you can download with chrome then you should be able to download with [Fennec](https://f-droid.org/packages/org.mozilla.fennec_fdroid/). Try once with Fennec F-Droid.

**Comment by Herbstfreud** [comment]
That's cool with ScreenCam. :-)
Where should I upload the video to? To the Telegram Channel?

By the way, with Fennec it works! That's interesting because I am sure I tried this also a few weeks ago and it didn't work...

**Comment by Avizini** [comment]
I can confirm this now, I did a factory reset yesterday and with Blokada I am also not able to download from browsers like Firefox Klar, which use android download manager.

**Comment by kar** [comment]
Can anyone having this issue confirm that Firefox Klar and others actually work under ordinary VPN apps?

**Comment by Avizini** [comment]
Yeahe everything works with a different VPN app, this is an issue with Blokada. Everything that uses android download manager is not working :(

**Comment by Herbstfreud** [comment]
@kar:
Would it help to send you a logcat of this situation when I am trying to download something?

**Comment by tarakbumba** [comment]
Hi there. I'm also facing very same issue on my Mi Note 3 which runs on top of Android 7.1.1 based stock/Mine 9.1.4.0. I can't download anything using stock/Non-root Mi  Browser and Android download manager.

**Comment by noelkra** [comment]
I can confirm that. It's not working either under Android 8 and Firefox Klar. Can't download anything.

**Comment by jesusoterogomez** [comment]
I am experiencing the same issue. This is the same behavior as explained in https://github.com/blokadaorg/blokada/issues/79 , All Android download manager downloads are queued, and if you turn off Blokada before they time out, everything will start downloading.

It's inconvenient to whitelist all the apps where this is happening, because we still want to block the ads inside of these apps.

Right now, my dirty workaround is just disabling Blokada temporarily after I trigger downloads

**Comment by kar** [comment]
https://issuetracker.google.com/issues/37105245
https://github.com/julian-klode/dns66/issues/31

**Comment by Herbstfreud** [comment]
So is there any chance to get this issue fixed in the future by the AOSP team?

**Comment by Herbstfreud** [comment]
Is there still the same behaviour on Pie?

**Comment by colbycdev** [comment]
It doesn't block them on my phone, both Chrome and Firefox, the latter from F-Droid. This is Android 8.1 on Alcatel Tetra

On Nov 27, 2018 5:06 PM, Herbstfreud <notifications@github.com> wrote:

Is there still the same behaviour on Pie?

**Comment by racuna** [comment]
Same here.

I'm on MIUI 10, Android 8.2

**Comment by animeking9901** [comment]
Seems this was a issue with the download manager being outside the tunnel if whitelisted,try taking it off the whitelist(it's there by default) and try again. I've had this work before

**Comment by Herbstfreud** [comment]
This does not work for me... I still have the same behaviour that any download will be blocked.

**Comment by soredake** [comment]
Any progress on this?

**Comment by kar** [comment]
Reproducible on 4.3.5?

**Comment by youri--** [comment]
Yes.

I've had this issue ever since I first installed blokada a couple of months ago. Still have this issue with latest version:

blokada/4.3.5 (android-28 full official arm64-v8a OnePlus-OnePlus6 touch api compatible)
Android 9 (OxygenOS v9.0.9)

I've tried both with and without Android Download  Manager & Downloads excluded in system apps. Other excluded system apps:
com.android.carrierconfig
Drive
Duo
Photos
Gmail
Google Play Store
Phone/Message Storage
Telephone Services
(exact translation of these names may be off, because unfortunately I can't force blokada into English)

When for example blokada is active and I start Mixplorer and an update is available, I can see mixplorer.com was allowed (update check) in Host Log. Then I hit Download, but download doesn't happen. A few minutes later I get a < Download failed > notification. If I have blokada paused, it will start downloading immediately after tapping Download.

**Comment by Herbstfreud** [comment]
The issue is gone somehow... Maybe it was one of the Blokada updates, maybe it was one of the LineageOS/Android-Updates, I don't know.
Just started to download something by DuckDuckGo Browser accidentelly and it downloaded with Blokada activated.

**Comment by PrintableCharacter** [comment]
If you think it's fixed you can close this issue on your own discretion :)

**Comment by Herbstfreud** [comment]
But before that I'd like to know what happened exactly... Currently I don't know why it's working now and I think this should be clarified before closing this (for other people with the same issue).

In my opinion it is also possible that this has been fixed by a LineageOS update. Or maybe something else?

**Comment by youri--** [comment]
I just noticed there is activity on this issue, please don't close this issue.

I still can't download anything using any browser when Blokada is active - currently v4.4.4 on Android 9, OxygenOS 9.0.9 stock, not rooted, OnePlus 6 (A6003). I get the download prompt and click download, or long-press an image and tap Save, then nothing happens and a while later (10, 15 minutes?) I get a notification "download failed" for an unknown filename.

If I disable Blokada new downloads start immediately and downloads I initiated while Blokada was active, that didn't work, suddenly start downloading, so I sometimes end up with more than 1 copy of the file I was trying to save.
