### ISSUE TITLE
since v3.6 most normal traffic is blocked or slowed down

### ISSUE THREAD

**Issue by kenjiwhe** [blokadaorg/blokada#284]
since v3.6 most normal traffic is blocked or slowed down on my Huawei MAte 10 Pro, android v8.0
all previous versions of blokada ran fine and nothing changed on my phone that can explain this.

### Steps to reproduce
Reproduction is permanent, it happens all the time.

### Expected behaviour
Only adds block, not all trafic

### Actual behaviour
Internet is 'down' until I close blokada or add the relevant app that lost connection to the blokada whitelist

### Configuration
1. Blokada version 3.6

2. Device model
huawei mate 10 pro

3. Android version / ROM
android 8.0

### Questions
1. How long have you been using Blokada? 
over a year

2. How long time ago has the problem started to happen? 
since v3.6

3.  How often does this problem happen to you?
all the time

**Comment by kar** [comment]
Go to your battery settings, find Blokada, disable "launch control". Huawei kills vpn requests after some time otherwise.

**Comment by kenjiwhe** [comment]
OK, thanks. But this only surfaced since v3.6

**Comment by milosvvv** [comment]
I also have a similar problem on Xiaomi Pocophone F1 with MIUI 9, Android 8.1 

Sporadically the internet would just stop working on WIFI due to Blokada. If I disable Blokada it works again, enabling Blokada again causes the issue so I cannot just switch Blokada off and back on. 
When this happens, switching off WIFI and using mobile network continues to exhibit the issue. When this happens, opening blokada shows no issues, it appears to work as normal, and switching off/on doesn't fix it.

Doing a force close on Blokada and then switching it back on makes everything work as expected again, until the next time this happens. Which has been quite often. I think it also starts happening on mobile network but need to continue observing.

I've added Blokada to not use battery saving features in MIUI and have not seen any change. I will continue to try and reproduce this or try to find something in common that happens right before the issue shows up

**Comment by kar** [comment]
Thank you. Please try choosing any custom dns (ex cloudflare).

**Comment by rpeter85** [comment]
Which DNS server did you use at work? If the network isn't routed to DNS, no name resolution can work, which causes the internet access will fail.

**Comment by milosvvv** [comment]
I was using the device DNS servers, I've now switched to Cloudflare within Blokada and will see if issue persists

**Comment by milosvvv** [comment]
ugh, using cloudflare DNS the ads don't get blocked at all, using device DNS or google DNS or OpenDNS they do. This 3.6 version has been such a disaster. On my previous device which I had until a month ago (Huawei P9) the new version was also a disaster, it would annihilate the battery and cause all kinds of issues, had to use the old version on that device.

**Comment by rpeter85** [comment]
How DNS lookup works on android:
The system will check the hosts file if there are hostnames and IP address binds.
If the hostname you typed isn't in the hosts file, it will go to the DNS server to resolve the hostname to IP address.
If that happened, will show you the content.

How Blokada comes into the picture and why it uses a VPN: before the hosts file is checked, Blokada filters through the lists you enabled in Blokada if there is a match. If yes, the host is redirected to the IP that's on the list. If not, it will let the hostname be handled by the system and the above steps are done.
It means if you have blacklists, the ad-blocking is independent from the DNS servers (however, the DNS server also can block ads, for example Keweon).
So something else goes on on your device if the ads aren't blocked even if Blokada is turned on.

**Comment by lijuenc** [comment]
Same issue on the Samsung Galaxy S9.

Others have also reported it here https://github.com/blokadaorg/blokada/issues/139. Not sure why that issue is closed when it's clearly still an ongoing thing.

The only way to restore functionality is to restart the device. At this point I'm forced to restart my device every 1-2 days because of Blokada.

**Comment by rpeter85** [comment]
based on @milosvvv comment, it seems the VPN wasn't able to restore its state.
Do you know if there were new updates for your phone? A security patch or anything? What DNS machines do you use, guys?

**Comment by milosvvv** [comment]
I no longer get blocked internet but it just fixed itself, I didn't touch anything. Sometimes it does stop blocking ads every now and then and I go through th eusual disable and enable and force close and whatever needs doing to get it working again.

It fixed itself before this, but I recently updated to MIUI 10 which is Android 8.1.0 with October security patch. There is also now a new setting under VPN to set a specific VPN to be an "Always-on VPN" and after setting this it seems to work much better than before. Watchdog is switched on as well.

I'll keep watch for the issue of it no longer blocking ads and see what I can report.

**Comment by rpeter85** [comment]
For the misbehaviour where you have to reset Blokada: http://go.blokada.org/help#kill
If you use Miui, and seems you do, go to the recent app page and tap on the lock in the top corner, that will ensure Blokada is kept in memory and doesn't killed by the system.

If you enabled "Always-on VPN" and did the steps that are documented on the link I shared above, you don't need the Watchdog.
Let us know if you face the same issue again.

@lijuenc, what about your phone? Did you get system updates recently?

**Comment by lijuenc** [comment]
My Samsung Galaxy S9 is running Android 8.0 with the October 2018 security patch. I'll try the "Always-on VPN" option and see if it makes a difference.

**Comment by lijuenc** [comment]
Enabling the "Always-on VPN" setting for Blokada's VPN didn't make any difference on my Samsung Galaxy S9 over the past couple of days. In about 80% of cases  when switching between mobile data and wi-fi all connectivity is lost. I can force close Blokada and restart it but it usually takes many tries to get it working again so the only consistently reliable way to restore it is to restart the phone.

**Comment by animeking9901** [comment]
From my watching if I recall a lot of newer or new Samsung have issues.
Don't we have a issue open for that?

**Comment by basaldella** [comment]
Galaxy S9 plus user here, I am experiencing this problem too. I have exactly  the same issue described in #139 (which by the way should be open, as the bug is not solved): when I switch from mobile to Wi-Fi, Blokada blocks all the traffic. 

On my Lenovo P2 Blokada works fine though. The Lenovo runs Android 7.0.1, while my S9+ runs on Android 8 with the latest updates.

**Comment by colbycdev** [comment]
Samsung phones tend to have issues with certain apps. It's their customizations. I've used an S8, and I develop apps. You basically have to develop for them specifically. But yes, is there a specific pattern other than switching network?

Warmest regards,
Colby Combs, Innonetlife Founder

________________________________

**Comment by basaldella** [comment]
I'm not sure is the same issue - here we're talking about traffic blocked *all the time*, while us Samsung owners have problems only after a network switch.

**Comment by rpeter85** [comment]
Samsung phones face the issue that traffic is blocked when switching network.
Can we focus on the issue and collect some information we can use to avoid such a behaviour in an upcoming version?

**Comment by animeking9901** [comment]
It appears android 8.1 Is also a common factor on these devices,I'll setup Android-x86 when I get home and verify,if x86 binaries are available

**Comment by rpeter85** [comment]
add 4 Samsungs, reported on Telegram.

**Comment by quaqo** [comment]
> add 4 Samsungs, reported on Telegram.

So it would be:

```
=======================================================
Vendor		#	Android Version
=======================================================
Huawei		3	8.0 (EMUI 8)
Samsung		4	8.0 (with October Security Patch)
Samsung		4	???
Samsung		1	8.1
OnePlus		1	9.0
Xiaomi		1	8.1 (MIUI 9) -> Seems (?) by upgrading to MIUI 10 (8.1 with October Security Patch)
=======================================================
```

**Comment by milosvvv** [comment]
I reported the Xiaomi and I no longer have the issue but I'm not sure what I did as I was messing with the settings even before upgrading to MIUI 10. I did disable battery savings for the app, "locked" it in task manager so it doesn't get killed, enabled "start in background" on app settings and set it as an Always-on VPN. Watchdog now makes no difference, it works the same enabled or disabled, I keep it disabled. So umm.. it is still somewhat of a mystery what happened but I'm happy it works.

**Comment by rpeter85** [comment]
Warming this topic up, do you guys found any pattern that we can use to reproduce the issue?

**Comment by slivabox** [comment]
Had had the same issue on s9 with v3.6 had to roll back to 3.4 otherwise was usable.

The issue appeared to be triggered by switch to WiFi from cellular and vice versa.

**Comment by alexanderadam** [comment]
This issue happens on [other phones with **Oreo 8.1**](https://piunikaweb.com/2017/12/21/google-fixes-android-8-1-wifivpn-issue/) too (but mostly S9, S9+, Pixel and LG G6). It's _not_ exclusively an Blokada issue. It will also happen on all other **VPN based** blockers (see also [the issue on DNS66](https://github.com/julian-klode/dns66/issues/258).

Triggering a reinitialisation seems to work in different reports.
So I guess if there would be a check whether the connection is working every now and then a reinitialisation could be triggered (i.e. after a negative health check result -> reinit & wait for a moment -> second check -> inform the user that there might be connection issues if it still won't work).

The idea of a health check was already discussed in [issue 255](https://github.com/blokadaorg/blokada/issues/255)  (I was running into the same situation of having blocked nothing [blokada issue] and everything [this issue here]).

**Comment by rpeter85** [comment]
@alexanderadam can you activate Watchdog in the advanced settings and check if you still face the same issue?

**Comment by alexanderadam** [comment]
@rpeter85 **TL;DR:** No.

Because I got the Android 9 / Samsung One update and, as reported before, the error doesn't appear anymore since the upgrade

Instead I slided directly into the Android 9 issues #237 / #257 so I had to deactivate `Async DNS Resolver` (not a good thing IMHO) and I had to activate `Keep alive` because Blokada somehow got killed (_although_ it still showed the notification) and didn't work anymore without it. In my case Blokada now also shows two notifications with the last blocked item (`Blocked example.org` and `12345 blocked — Last: example.org`). So I have new issues now but they are much better than the "not being able to use internet at all" issue here. :wink:

**Comment by natecraddock** [comment]
I am having the exact same problem with v3.6. On my Samsung s9 (running android 8.0) the second Blokada is enabled all internet traffic is blocked. I have tried all combination of settings I can think of, and many of the DNS servers.

**Comment by cubagithub** [comment]
Same problem with v3.6 on HTC 10 pme.
Watchdog, keepalive, always on VPN options enabled.
No non-whitelisted apps have internet access.

**Comment by meden** [comment]
Same problem with Honor 6x (Android 7.0). So, not an Android 8 only issue (as alleged by @alexanderadam).

**Comment by meden** [comment]
I can confirm that downgrading to 3.4 solves the issue for me too. So, it seems that the issue is definitely in Blokada 3.6, not in Android nor on specific phones only. It has nothing to do with power saving features neither, it seems (beside the usual and expected behavior).

Reproducing it is easy as put the phone in flight mode and then re-enable connectivity. Blokada v3.6 blocks all traffic (included DNS, as I get "name unknown" errors in web browsers), while v3.4 works as intended blocking only ads.

The bug is tagged as `input-needed`: which kind of input is still needed? How can I help? This is a showstopper, to me, as I cannot rely on Blokada anymore (I cannot now if my connectivity still works and I keep missing push notifications...).

Thanks

**Comment by alexanderadam** [comment]
@meden maybe there is simply _more than one_ possibility to cause this issue. Because in my case it was solved by upgrading Android. And not only that: [as I wrote earlier](https://github.com/blokadaorg/blokada/issues/284#issuecomment-448302991) other applications had the exact same issue (click the links to these issues to get more information on that).

PS: Your case probably strengthens my opinion that a generic health check that could trigger a reinitialization would be useful to help in issues like this one (see [255](https://github.com/blokadaorg/blokada/issues/255)).

**Comment by basaldella** [comment]
I confirm that upgrading my S9+ to Pie resolved all the issues with Blokada 3.6; now I use it all the time and it just works. 

However, I also confirm that with Android 8, downgrading to 3.4 was a viable solution for me.

**Comment by zhengjie-lim** [comment]
Just wanted to chime in on this issue, currently on note 9 with Android 8.1 oreo and it seems to run fine with Blokada 3.3.

**Comment by Aciz** [comment]
Blokada 3.6 & OnePlus 6 with Android 9, disconnecting numerous times a day.

**Comment by meden** [comment]
@alexanderadam of course there could be (and most likely there is) some underlying platform issue/change causing this issue. But still:
1. It's unclear what new input is needed to help in solving the issue.
2. Going through other similar FOSS project (i.e. based on always on VPN), the issue was solved by just resetting the connection (as you suggested).
3. The issue is critical because renders the software unusable, and worse because you cannot rely on phone connectivity anymore (it's enough to connect/disconnect to a WiFi network without noticing and you're likely done).
4. It clearly depends not only on the underlying platform, but also on some specific Blokada changes, because otherwise even the 3.4 version would be affected.

It seems to me that there is enough data to look for/implement a solution, that's why I was asking which additional input is still needed to consider this as a "real" (critical) bug and try to fix it ASAP.

(As a side note: of course I know this is a free open source software, that I could fix it by myself and make a PR, and so on: I'm not requiring anything from anyone :) )

**Comment by alexanderadam** [comment]
@meden 
1. There aren't [a lot of contributors](https://github.com/blokadaorg/blokada/graphs/contributors) so far and if I understand correctly what was written here, the developers don't have a device where they can reproduce this issue at the moment. So it's probably rather unclear how they can reproduce the bug. Furthermore they might just not have enough time to work on it.
2. Actually [the issues on DNS66](https://github.com/julian-klode/dns66/issues/258), [AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/issues/1770), [orbot](https://github.com/n8fr8/orbot/issues/151) [[1](https://github.com/n8fr8/orbot/issues/151), [2](https://github.com/n8fr8/orbot/issues/162)] and [shadowsocks](https://github.com/shadowsocksrr/shadowsocksr-android/issues/90) I mentioned before are still open and unfixed.
3. I guess this is clear for everyone. It won't change anything though. It would still need someone who fixes this. And it seems that it isn't critical enough that you are creating a pull request, right? :wink: 
4. [I explained exactly that four days ago already: maybe there is simply more than one possibility to cause this issue. Because in my case and other people it was definitely solved by upgrading Android.](https://github.com/blokadaorg/blokada/issues/284#issuecomment-454011196)

> It seems to me that there is enough data to look for/implement a solution[…]. I know this is a free open source software, that I could fix it by myself

Awesome! :+1:  That sounds good. Do you know already when you can deliver a bugfix?

**Comment by Aciz** [comment]
@rpeter85 I might have not. I'll go back to 3.6 for now and make sure to disable all optimizations, and see what happens.

**Comment by xmiseggs** [comment]
Well, I want to give my input. I have a OnePlus 5T with Android 8 and Blokada 3.6 

Option 1
Without doing anything special, after a few hours I see that the application is not there, android has closed it.

Option 2 
If in recent applications to Blokada I put the padlock closed so that it does not close, the system ends up closing.

Option 3 
With the padlock (option 2) and the "Keep active" option activated with the notification minimized (because I don't like having it above all on the lock screen), the system ends up closing.

Option 4
With everything from option 3, 2. Enabling the Android 9 option "VPN always on" for the moment is kept running.

I'll keep watching.


I also wanted to comment that with the last beta of Adguard and only with option 2 it remains active and does not close.

**Comment by rpeter85** [comment]
Anybody who faces the issue reported in the initial message, could you try to use/enable a 3rd party DNS server (from the list you can find in Blokada) and test if you face the same issue? This way we can narrow down it a bit.

**Comment by xmiseggs** [comment]
It is true @basaldella , but following the post also here is dealing with the closure of the Blokada application, in that case I will open another post. Thank you

**Comment by rpeter85** [comment]
@miseggs don't need. Exclude Blokada feom. every memory- and  attery optimisation. Check your system's settings.

**Comment by meden** [comment]
> Awesome!  That sounds good. Do you know already when you can deliver a bugfix?

Yes, I already have one: I installed [Netguard](https://www.netguard.me/), which is not affected by this bug (just as Blokada 3.4, BTW) and has firewall features too, despite not being so polished as Blokada. Maybe is not as good as Blokada (haven't done thorough tests), but it is enough form me.

Look, I'm sorry this conversation went bitter: I just asked why this bug is still tagged as `input-needed` and what kind of "input" I could give to help. The answer has been "Then fix it by yourself", as too often still happens in the FOSS community.

Moreover, Blokada 3.4 works properly, so one cannot just say "it's probably an Android bug": maybe it is a combination of factors, but if a previous version of the same software works under the very same conditions, well, then definitely something _in the software_ is triggering the alleged OS bug.

That said, good luck, and thanks for your work anyway.

**Comment by xmiseggs** [comment]
@meden I agree with you and I think the same as you.

**Comment by rpeter85** [comment]
So instead of trying to help us figure out what happens (see my comments), you just walk away.
It's tagged as 'Input needed' because we couldn't reproduce. We asked for more information, ways you tried to overcome the situation, but the only answer was "restart the phone". Awesome.

**Comment by alexanderadam** [comment]
>> Awesome! That sounds good. Do you know already when you can deliver a bugfix?

> Yes, I already have one: I installed Netguard

I don't think that this is the meaning of the word "deliver" :wink: 

> I just asked why this bug is still tagged as input-needed and what kind of "input" I could give to help.

See, I might be wrong on this but [**rpeter85** just asked for feedback](https://github.com/blokadaorg/blokada/issues/284#issuecomment-456872315) to tackle this issue. So instead of actually helping you just commented about stuff that won't help anybody (usually known as trolling).

> The answer has been "Then fix it by yourself" […]

Actually nobody said that. I just asked because you claimed…

> It seems to me that there is enough data to look for/implement a solution […] I could fix it by myself […]

**Comment by milosvvv** [comment]
I would love to help but the thing is that this is such a sporadic and nonsensical issue that I cannot find any meaningful commonalities between each occurrence. 

I have a Xiaomi Pocophone F1 and was in the first posts of this thread reporting the issue. My version now is MIUI Global 10.2 Stable, Android 9, security patch 01-12-2018. Over the course of using Blokada with this phone and Android 8 and 9 I've gone through all the described issues: from no internet ever, to no internet when switching connections, to no ad blocking but internet working, to it working fine for days and days on end.

Right now only one issue remains, that sometimes when switching from 4G to WiFi the data connection would stop working and I wouldn't be able to browse anything. Solution so far has been to go into Blokada and stop protection, then go and Force kill the app, then open it again and enable protection (disabling and enabling protection without force kill doesn't work) The only commonality I've found it that this happens when I'm on 4G for a long time and then switch to WiFi, but when the switch is not in such long intervals then it works fine.

No clue at all why this issue has survived and even mutated between different Android versions and different months of usage. Completely baffled here.

**Comment by rpeter85** [comment]
Try with a 3rd party DNS machine. Our impression is that the DNS server set to 192.168.0.1 or 192.168.1.1 on system level, that Blokada can't reach as it creates a tunnel through the router, therefore it can't address it.
So, if you could set a DNS, other than the default, and could check if you are facing the issue, could help us to narrow down the possible causes.

**Comment by quaqo** [comment]
> Try with a 3rd party DNS machine. Our impression is that the DNS server set to 192.168.0.1 or 192.168.1.1 on system level, that Blokada can't reach as it creates a tunnel through the router, therefore it can't address it.
> So, if you could set a DNS, other than the default, and could check if you are facing the issue, could help us to narrow down the possible causes.

Hey. Thanks for the input. As said before I'm on Oreo 8.0 on Honor 8 (so EMUI). All battery optimizations off, etc. I tried what you suggested and waited a few days before commenting.

Short answer it does not work for me. I'm back to 3.4 which works fine. 

I'm planning on ADB debug tomorrow if I have some time to spare and I'll update if I find something interesting.

**Comment by rpeter85** [comment]
3 others are reported their issue with the blocked internet is solved by setting a 3rd party DNS server, but it seems there are different issues driving to the same breaking point.
Thanks for the debug, let us know your findings.

**Comment by zhengjie-lim** [comment]
Reporting in with note 9 on stock oreo 8.1 with Blokada 3.6.

Turned off battery optimization for Blokada. In Blokada settings, turned off keep alive, watchdog and aggressive wakeup.

Working fine for the past 12 hours, will update again in a few days.

**Comment by KSchuster09** [comment]
This happens to me when I switch between home wifi and work wifi

Galaxy S7
Blokada 3.6
  Keep alive on
  Watchdog off
  Default dns
Notes
 1) home net is on a 192 168.1.0/24 block along with the dns
 2) work is on a 172.16.0.0/12 block, and also has the dns server on it.
 
So, with that being said, I've noticed rapidly switching wifi on and off again would finally allow it to work on wifi. After digging into it, I noticed that blokada was continuing to set the default dns to my home dns. Haven't tried using any external dns servers at work yet.


With that being said, changing my wifi settings from dhcp to static (along with the correct dns servers) seems to fix the issue. I haven't tested changing the dns on the app yet, but can try that tomorrow.

**Comment by rpeter85** [comment]
Great, it means the app gets either a DNS that cannot be addressed or the DNS is cached somewhere (which isn't cached in Blokada) and reported to the application.
Anybody else had time to try what I wrote on the 24th? We can't go and fix it if only one user confirms the solution.

**Comment by milosvvv** [comment]
I've changed my DNS inside blokada to OpenDNS on the 25th and haven't had an issue since, switching between 4G and Wifi and back works fine. Will keep monitoring for any further issues.

**Comment by mattspew** [comment]
Same problem as others; total or partial loss of internet with Blokada v3.6 running. Restarting phone seems to be the best way to fix the problem. Only been using Blokada for about 3 weeks and only the last week has it been a problem.

Huawei Nova 3i, Android 8.1, Wifi(Google DNS) and mobile.

**Comment by natecraddock** [comment]
Since I last commented I did a few tests (including testing different DNS providers). What I found was interesting. When I first tried setting up Blockada a month ago I was on one network (I will call this network A). I gave up after it not working at all (no traffic was allowed). Then a week ago I heard to downgrade to 3.4 and I tried it with success (but at the time I was on network B.) Then after a few days without problems I went back to network A and the VPN didn't allow any traffic once again. As far as I can tell my problem was because of something to do with network A. I later tried 3.6 on network B with no problems. I'm not sure what the problem is, but I'm on network B far more than I am on network A so for now the issue is minimal.

**Comment by Trigtrig** [comment]
> 
> 
> Great, it means the app gets either a DNS that cannot be addressed or the DNS is cached somewhere (which isn't cached in Blokada) and reported to the application.
> Anybody else had time to try what I wrote on the 24th? We can't go and fix it if only one user confirms the solution.

Hello everybody,
i have the same bug already discussed here.
Device:
- Honor 8
- Android 8.0 (EMUI 8.0)
- Blokada v3.6

I have been following the discussion here for the last few days and have also tried out numerous solution ideas. Unfortunately none of them worked. Now I have changed the DNS server from "Default" to DNS.WATCH since a few days and don't have any connection interruptions anymore. So the solution seems to work for me.

**Comment by rpeter85** [comment]
Gals and gents,
We are preparing a new version that will ship the fix for the reported issue. Because most of you faced the initial behaviour, I'm reaching out to you to ask if you are open and will try this new, beta release to validate that the bug is resolved and the app is stable, ready to be public.
If you are so, join our Telegram channel (http://go.blokada.org/chat) and write to the admin Peter.

**Comment by meden** [comment]
> > > Awesome! That sounds good. Do you know already when you can deliver a bugfix?
> 
> > Yes, I already have one: I installed Netguard
> 
> I don't think that this is the meaning of the word "deliver" 

The tone of my answer was due to yours, where you say I was _trolling_. And BTW you forgot to quote where I say "I'm sorry if the conversation went bitter".

> > I just asked why this bug is still tagged as input-needed and what kind of "input" I could give to help.
> 
> See, I might be wrong on this but [**rpeter85** just asked for feedback](https://github.com/blokadaorg/blokada/issues/284#issuecomment-456872315) to tackle this issue. So instead of actually helping you just commented about stuff that won't help anybody (usually known as trolling).
> 
> > The answer has been "Then fix it by yourself" […]
> 
> Actually nobody said that. I just asked because you claimed…
> 
> > It seems to me that there is enough data to look for/implement a solution […] I could fix it by myself […]

I wrote that "disclaimer", because I was foreseeing your very same answer. And I was right. BTW, here too you forgot to quote my whole sentence (smiley included):
> (As a side note: of course I know this is a free open source software, that I could fix it by myself and make a PR, and so on: I'm not requiring anything from anyone :) )

And last but not least, before the message that upset you (and your fellow colleague) I had posted (twice) my contribution (my phone model, how to _consistently_ trigger the bug, how the downgrade fixes it, plus some consideration on priorities: that's quite an amount of my spare time). But you just said that I'm trolling. Fine, but then you cannot expect that I'll stick here without looking for another project (and possibly other user-friendly developers).

This is my last post, needed because I don't want be depicted as a jerk when I just tried to help sorting out things.

Good luck (and congratulations for having found a solution, hopefully).

**Comment by dyingjedi** [comment]
#beta37volunteer - in this thread says to contact Alex in telegram correct?

Samsung Galaxy Note9 w/512GB internal edition

Android version
8.1.0
Samsung Experience version
9.5
Baseband version
N960USQU1ARL1
Kernel version
4.9.65
dpi@21HHAF04 #1
Fri Dec 14 19:20:17 KST 2018
Build number
M1AJQ.N960USQU1ARL1
SE for Android status
Enforcing
SEPF_SM-N960U_8.1.0_0007
Fri Dec 14 19:25:27 2018
Knox version
Knox 3.2
Knox API level 26
TIMA 4.1.0
Service provider SW ver.
SAOMC_SM-N960U_OYN_VZW_OO_0046
294d05b51b047ece
VZW/VZW/VZW
Security software version
MDF v3.1 Release 3
WLAN v1.0 Release 2
VPN PP-MOD v2.1 Release 1.1
ASKS v1.4.5 Release 180410
ADP v1.0 Release 180525
FIPS BoringSSL v1.2.1
FIPS SKC v1.9
FIPS SCrypto v2.2
SMR Dec-2018 Release 1
Android security patch level
December 1, 2018

could this be a similar issue blokada is also doing reconfiguring each time network changes? 

maybe an alternative solution when connected to mobile or Wi-Fi or USB Network adapter, let user create a role/rule profile for that specific connection to not reconfigure and to reuse previous netd configuration?  but which also creates horrible kinds of trouble because of cell phone tower switching which also brings down blokAda. every tower exchange creates the problem. the solution I created was a full-time T-Mobile device as a hotspot so my phone won't try to connect everything around it constantly. which is temporarily a fix while driving around the cities.

Adguard support came up with a great fix that's actually working. see below for all related links to my references and researching this morning/afternoon. I suggested in telegram which I'll paste here also.

As a temporary solution, please ask customers to enable pref.vpn.disable.reconfiguration, reboot the device and see how it goes

https://github.com/AdguardTeam/AdguardForAndroid/issues/1770#issuecomment-373628180
   
	As a temporary solution, please ask customers to enable pref.vpn.disable.reconfiguration, reboot the device and see how it goes.

 Apparently the link below really explains the VPN BUG which is built into android itself. the actual bug & what's the plan to fix it. in android what's happening is when the netD service goes to add the new VPN it's still in the processing the destroy CMD & that will cause the previous connection and newly add service to conflict apparently.

https://issuetracker.google.com/issues/76356827

https://github.com/ameshkov/TestVpnService&sa=D&usg=AFQjCNEo7arC6LAnrZFMuxCsjdOlFizxoA
    
	submit android bugs/crash report to - android-bugreport@google.com
    http://developer.samsung.com/forum/thread/vpn-is-broken-on-samsung-s9/201/346696?boardName=SDK&startId=zzzzz
    
https://ipleak.net/

**Comment by mattspew** [comment]
I don't have or want Telegram, can I get the beta APK another way?

**Comment by rpeter85** [comment]
Unfortunately no. Beta testing requires active communication and other platforms aren't sufficient for that, only chats.

**Comment by mattspew** [comment]
That's a shame; I'm having regular problems on my Huawei, got worse after upgrading to Android 9.

Blokada can't handle going between network and often I find it frozen in the background slowing traffic to a crawl. I find myself force killing the app several times a day. Will even freeze and need killing without even changing networks over night.

**Comment by rpeter85** [comment]
This fix for the blocked or slowed down network access is shipped in version 3.7, that is released today.
Thank you for reporting this bug and helping us to fix it.

**Comment by mattspew** [comment]
Since the upgrade to 3.7, "Default DNS" is detected as "1.1.1.1, 1.0.0.1" on both mobile and wifi.

**Comment by rpeter85** [comment]
That is to get over the situation. Turn off "DNS fallback" and you will see the 192.168.x.y, which cannot be addressed and therefore you can browse the internet.

**Comment by mattspew** [comment]
My router uses Google DNS anyway, should I just turn off Default DNS and turn on Google DNS?

**Comment by quaqo** [comment]
> That is to get over the situation. Turn off "DNS fallback" and you will see the 192.168.x.y, which cannot be addressed and therefore you can browse the internet.

Thanks @rpeter85. It works very well, I understand it was difficult to pinpoint the exact problem.

I took a look at the "fallback" code; may I ask why there's this problem now with not being able to reach local addresses on Oreo (or other Android vendors fashions) that was not present in 3.4 (and maybe 3.5)?

**Comment by svenjacobs** [comment]
I, too, face this issue on a Google Pixel 3 XL with Android 9.0.

_Keep alive_ is turned on. DNS is standard.
_Battery optimisation_ was turned on automatically by Android. I turned it off now and will see if it improves the situation.

**Comment by rpeter85** [comment]
@svenjacobs the issue is fixed in 3.7, please download and use that version.
